version: '2.2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
    environment:
      - TZ='Canada/Toronto'
      - PLEX_CLAIM=<PLEX CLAIM GOES HERE>
    hostname: <HOSTNAME GOES HERE>
    volumes:
      - './plex-config/:/config'
      - './plex-transcode/temp/:/transcode'
      - /mnt/media:/video
      - /mnt/audio:/audio
    cpus: 4
    mem_limit: 4g
