version: "2.4"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "0.0.0.0:53:53/tcp"
      - "0.0.0.0:53:53/udp"
      - "81:80/tcp"
      - "444:443/tcp"
    environment:
      TZ: 'Canada/Toronto'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    cpus: 1
    mem_limit: 1g
